package atlas

// This file renders one ir.Module into one Atlas HCL schema file: a
// `schema "<name>" {}` block per distinct Postgres schema used by the
// module's entities, followed by one `table "<table>" { ... }` block per
// entity holding its columns, primary key, indexes, and foreign keys.

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/zenta-dev/zever/dsl/ir"
)

// generatedHeader is prepended to every emitted .hcl file.
const generatedHeader = "// Code generated by the zever DSL atlas backend. DO NOT EDIT.\n"

// defaultSchema is the Postgres schema used when a module declares no
// entities at all, so every generated file still contains at least one
// addressable schema block.
const defaultSchema = "public"

// atlasIdentRe matches a bare HCL identifier: what schema.<name> reference
// expressions require (see renderModuleFile's validation loop). Atlas/HCL
// identifiers are ASCII letters/digits/underscore, not starting with a
// digit -- the same shape a Postgres unquoted identifier already requires,
// so this is not a new restriction beyond what a schema name needs anyway.
var atlasIdentRe = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// renderModuleFile renders one module into its output-relative file path
// ("<module>/schema.hcl", or "schema.hcl" for the implicit unnamed module)
// and its Atlas HCL content.
func renderModuleFile(m *ir.Module) (path string, content []byte, err error) {
	path = "schema.hcl"
	if m.Name != "" {
		path = m.Name + "/schema.hcl"
	}

	var b strings.Builder

	b.WriteString(generatedHeader)

	schemas := moduleSchemas(m)

	// Every schema name renderTable will later reference as schema.<name>
	// is drawn from this same set, so validating it here covers every
	// reference site: unlike renderTable's %q-quoted table/column names
	// (plain HCL string literals, safe with any text), a schema
	// REFERENCE ("schema = schema.<name>") is bare HCL identifier syntax
	// that cannot be quoted at all -- @schema(...) accepts an arbitrary
	// string literal at the resolver (resolveSchemaAttribute), so a value
	// containing HCL-structural characters must be rejected here rather
	// than spliced in unquoted, which would let it inject or malform HCL
	// structure in the generated migration file.
	for _, name := range schemas {
		if !atlasIdentRe.MatchString(name) {
			return "", nil, fmt.Errorf("atlas: @schema value %q is not a valid HCL identifier (must match %s)", name, atlasIdentRe.String())
		}
	}

	for _, name := range schemas {
		fmt.Fprintf(&b, "\nschema %q {\n}\n", name)
	}

	for _, enum := range m.Enums {
		renderEnumType(&b, enum)
	}

	fks := collectForeignKeys(m)
	seenTables := make(map[string]string, len(m.Entities))

	for _, e := range m.Entities {
		table := TableName(e)

		if prev, dup := seenTables[table]; dup {
			return "", nil, fmt.Errorf(
				"atlas: entities %s and %s both map to table %q", prev, e.Name, table)
		}

		seenTables[table] = e.Name

		renderTable(&b, e, fks[table])
	}

	return path, []byte(b.String()), nil
}

// moduleSchemas returns the distinct, sorted Postgres schema names used by
// a module's entities, falling back to "public" for a module with none.
func moduleSchemas(m *ir.Module) []string {
	set := make(map[string]bool, len(m.Entities))

	for _, e := range m.Entities {
		name := e.Schema
		if name == "" {
			name = defaultSchema
		}

		set[name] = true
	}

	if len(set) == 0 {
		return []string{defaultSchema}
	}

	out := make([]string, 0, len(set))
	for name := range set {
		out = append(out, name)
	}

	sort.Strings(out)

	return out
}

// renderEnumType writes one named enum as an Atlas HCL `enum` block, so
// fields referencing it (via atlasColumnType) can share one declared type
// instead of each emitting its own. Uses defaultSchema: ir.Enum carries no
// per-declaration @schema of its own (unlike ir.Entity), and named enums are
// global rather than owned by one entity's schema.
func renderEnumType(b *strings.Builder, enum *ir.Enum) {
	fmt.Fprintf(b, "\nenum %q {\n", enumTypeName(enum.Name))
	fmt.Fprintf(b, "  schema = schema.%s\n", defaultSchema)

	values := make([]string, len(enum.Values))
	for i, v := range enum.Values {
		values[i] = fmt.Sprintf("%q", v)
	}

	fmt.Fprintf(b, "  values = [%s]\n", strings.Join(values, ", "))
	b.WriteString("}\n")
}

// renderTable writes one entity's `table` block, including every foreign
// key attributed to that table (which may originate from a has_one
// relation declared on a different entity).
func renderTable(b *strings.Builder, e *ir.Entity, fks []foreignKey) {
	schemaName := e.Schema
	if schemaName == "" {
		schemaName = defaultSchema
	}

	nullable := nullableColumns(fks)

	fmt.Fprintf(b, "\ntable %q {\n", TableName(e))
	fmt.Fprintf(b, "  schema = schema.%s\n", schemaName)

	for _, f := range e.Fields {
		fmt.Fprintf(b, "  column %q {\n", f.Name)
		fmt.Fprintf(b, "    null = %t\n", nullable[f.Name] || f.Optional)
		fmt.Fprintf(b, "    type = %s\n", atlasColumnType(f))
		b.WriteString("  }\n")
	}

	if pk := primaryKeyField(e); pk != nil {
		b.WriteString("  primary_key {\n")
		fmt.Fprintf(b, "    columns = [column.%s]\n", pk.Name)
		b.WriteString("  }\n")
	}

	for _, idx := range entityIndexes(e) {
		fmt.Fprintf(b, "  index %q {\n", idx.Name)
		fmt.Fprintf(b, "    unique  = %t\n", idx.Unique)
		fmt.Fprintf(b, "    columns = [%s]\n", columnRefs(idx.Columns))
		b.WriteString("  }\n")
	}

	for _, fk := range fks {
		renderForeignKey(b, fk)
	}

	b.WriteString("}\n")
}

// renderForeignKey writes one `foreign_key` block inside a table block.
func renderForeignKey(b *strings.Builder, fk foreignKey) {
	fmt.Fprintf(b, "  foreign_key %q {\n", fk.Name)
	fmt.Fprintf(b, "    columns     = [column.%s]\n", fk.Column)
	fmt.Fprintf(b, "    ref_columns = [table.%s.column.%s]\n", fk.RefTable, fk.RefColumn)

	if action := onDeleteHCL(fk.OnDelete); action != "" {
		fmt.Fprintf(b, "    on_delete   = %s\n", action)
	}

	b.WriteString("  }\n")
}

// columnRefs renders a column list as Atlas column references, e.g.
// "column.user_id, column.status".
func columnRefs(columns []string) string {
	refs := make([]string, 0, len(columns))
	for _, c := range columns {
		refs = append(refs, "column."+c)
	}

	return strings.Join(refs, ", ")
}

// atlasColumnType maps a field's scalar type to the Atlas/Postgres column
// type emitted in HCL.
//
// A named TEnum field references the shared `enum` block rendered by
// renderEnumType (type = enum.<name>); an anonymous inline enum(...) field
// still maps to plain text, since there is no shared declaration to
// reference.
func atlasColumnType(f *ir.Field) string {
	switch f.Type.Scalar {
	case ir.TUUID:
		return "uuid"
	case ir.TString:
		if n, ok := maxLen(f); ok {
			return fmt.Sprintf("varchar(%d)", n)
		}

		return "text"
	case ir.TInt32:
		return "int"
	case ir.TInt64:
		return "bigint"
	case ir.TFloat32:
		return "real"
	case ir.TFloat64:
		return "double_precision"
	case ir.TBool:
		return "boolean"
	case ir.TTimestamp:
		return "timestamptz"
	case ir.TDate:
		return "date"
	case ir.TBytes:
		return "bytea"
	case ir.TJSON:
		return "jsonb"
	case ir.TEnum:
		if f.Type.EnumName != "" {
			return "enum." + enumTypeName(f.Type.EnumName)
		}

		return "text"
	}

	return "text"
}
