// Package gengrammar generates the editor grammar files shipped under
// editors/nvim/syntax/zen.vim and editors/vscode/syntaxes/zen.tmLanguage.json
// from the DSL compiler's own tables (token.Keywords and
// resolver.ScalarTypeNames), so those two tables are the single source of
// truth for both editor integrations instead of hand-maintained,
// independently drifting copies.
//
// Both generated files also declare a fixed set of contextual block labels
// and HTTP verbs (e.g. "http", "auth", "GET") that are plain identifiers to
// the lexer -- no compiler table backs them, since they are only meaningful
// by position, not reserved. Labels and Verbs below are the sole source for
// those two lists; keep them in sync with the parser packages named in
// their doc comments if the DSL's contextual labels change.
//
// VimSyntax and TmLanguage are pure functions of those tables: for a fixed
// keyword/scalar/label/verb set they always produce the same bytes, which
// is what lets `make generate` be deterministic and lets
// editors/parity_test.go diff their output against the checked-in files.
package gengrammar

import (
	"fmt"
	"sort"
	"strings"

	"github.com/zenta-dev/zever/dsl/resolver"
	"github.com/zenta-dev/zever/dsl/token"
)

// VimPath and TmPath are the checked-in grammar files' locations, relative
// to the repository root.
const (
	VimPath = "editors/nvim/syntax/zen.vim"
	TmPath  = "editors/vscode/syntaxes/zen.tmLanguage.json"
)

// Labels lists the contextual block labels and attribute names used inside
// rpc/job/schedule/entity bodies -- see internal/dsl/parser/parser_service.go,
// parser_job.go, parser_schedule.go, and parser_entity.go for the block
// labels, and resolver_entity.go, resolver_relation.go, resolver_service.go,
// resolver_message.go for the attribute names. They are plain identifiers
// at the lexer level, only meaningful by position, so no compiler table
// pins them down; this slice is the sole source for both grammars.
var Labels = []string{
	"http", "auth", "permission", "queue", "retry", "cron", "dispatch",
	"join_table", "foreign_key", "on_delete", "validate", "default",
	"primary", "unique", "required",
}

// Verbs lists the HTTP verbs recognized after an `http:` label, e.g.
// `http: GET "/tasks"`.
var Verbs = []string{"GET", "POST", "PUT", "PATCH", "DELETE"}

// Booleans lists the boolean literals. They are keywords to the lexer
// (token.TRUE/token.FALSE) but highlighted as a distinct group in both
// grammars.
var Booleans = []string{"true", "false"}

// Keywords returns the sorted list of reserved words from token.Keywords,
// excluding the boolean literals (Booleans covers those separately).
func Keywords() []string {
	out := make([]string, 0, len(token.Keywords))

	for w := range token.Keywords {
		if w == "true" || w == "false" {
			continue
		}

		out = append(out, w)
	}

	sort.Strings(out)

	return out
}

// ScalarTypes returns the sorted list of builtin scalar type names, from
// resolver.ScalarTypeNames -- the DSL compiler's source of truth for the
// v1 scalar type set.
func ScalarTypes() []string {
	return resolver.ScalarTypeNames()
}

// Files returns the generated content for every grammar file, keyed by its
// path relative to the repository root (VimPath, TmPath).
func Files() map[string][]byte {
	return map[string][]byte{
		VimPath: VimSyntax(),
		TmPath:  TmLanguage(),
	}
}

// VimSyntax renders the Vim :syntax file for the zen DSL (.zen files).
func VimSyntax() []byte {
	var b strings.Builder

	b.WriteString(vimHeader)
	fmt.Fprintf(&b, "syntax keyword zenKeyword %s\n\n", strings.Join(Keywords(), " "))
	fmt.Fprintf(&b, "syntax keyword zenBoolean %s\n\n", strings.Join(Booleans, " "))
	b.WriteString(vimTypeComment)
	fmt.Fprintf(&b, "syntax match zenType \"\\<\\%%(%s\\)\\>\"\n\n", strings.Join(ScalarTypes(), `\|`))
	b.WriteString(vimLabelComment)
	fmt.Fprintf(&b, "syntax match zenLabel \"\\<\\%%(%s\\)\\>\\s*:\"me=e-1\n\n", strings.Join(Labels, `\|`))
	b.WriteString(vimVerbComment)
	fmt.Fprintf(&b, "syntax keyword zenHTTPVerb %s\n\n", strings.Join(Verbs, " "))
	b.WriteString(vimFooter)

	return []byte(b.String())
}

// TmLanguage renders the TextMate grammar JSON for the zen DSL.
func TmLanguage() []byte {
	labelsAndVerbs := make([]string, 0, len(Labels)+len(Verbs))
	labelsAndVerbs = append(labelsAndVerbs, Labels...)
	labelsAndVerbs = append(labelsAndVerbs, Verbs...)

	out := fmt.Sprintf(tmTemplate,
		strings.Join(Keywords(), "|"),
		strings.Join(Booleans, "|"),
		strings.Join(ScalarTypes(), "|"),
		strings.Join(labelsAndVerbs, "|"),
	)

	return []byte(out)
}

// vimHeader is the static preamble shared by every generated vim grammar:
// the file banner and the current_syntax guard.
const vimHeader = `" Vim syntax file for the zen schema DSL (.zen files).
" Language: zen (github.com/zenta-dev/zever internal/dsl)
"
" Code generated by internal/dsl/gengrammar from internal/dsl/token.Keywords
" and internal/dsl/resolver.ScalarTypeNames; DO NOT EDIT the keyword,
" boolean, or type lines by hand -- run ` + "`make generate`" + ` instead. The
" contextual labels and HTTP verbs below have no compiler-side table (they
" are plain identifiers to the lexer) and are literal constants in
" internal/dsl/gengrammar/gengrammar.go.

if exists("b:current_syntax")
  finish
endif

" Reserved keywords -- see internal/dsl/token/token.go's Keywords map. This
" is the authoritative, lexer-level reserved word list (the structural
" keywords plus true/false, handled separately below).
" "module" is intentionally absent: module-block syntax was removed in
" v-next (modules are now derived from the directory), so it lexes as a
" plain identifier.
`

const vimTypeComment = `" Builtin scalar types (plain identifiers at the lexer level, not
" reserved -- see internal/dsl/resolver.ScalarTypeNames).
`

const vimLabelComment = `" Contextual block labels used inside rpc/job/schedule bodies (http, auth,
" permission, queue, retry, cron, dispatch, join_table -- see
" internal/dsl/parser/parser_service.go, parser_job.go, parser_schedule.go,
" parser_entity.go) plus the attribute names the resolver understands
" (foreign_key, on_delete, validate, default, primary, unique, required --
" see resolver_entity.go, resolver_relation.go, resolver_service.go,
" resolver_message.go). These are plain identifiers to the lexer, only
" meaningful by position, but it's helpful to color them distinctly.
`

const vimVerbComment = `" HTTP verbs following an ` + "`http:`" + ` label, e.g. ` + "`http: GET \"/tasks\"`" + `.
`

const vimFooter = `syntax match zenComment "//.*$" contains=@Spell

syntax region zenString start=/"/ skip=/\\"/ end=/"/ contains=@Spell

" Integers, floats, and duration literals (number immediately followed by
" one of the recognized suffixes: ns us µs ms s m h). Longest suffixes are
" tried first so e.g. "30ms" doesn't get chopped at "m".
syntax match zenNumber "\<\d\+\%(\.\d\+\)\?\%(ns\|us\|µs\|ms\|s\|m\|h\)\?\>"

" Attributes, e.g. @primary, @unique, @validate(...), @foreign_key(user_id).
syntax match zenAttribute "@\w\+"

syntax match zenOperator "->"

highlight default link zenKeyword Keyword
highlight default link zenBoolean Boolean
highlight default link zenType Type
highlight default link zenLabel Identifier
highlight default link zenHTTPVerb Special
highlight default link zenComment Comment
highlight default link zenString String
highlight default link zenNumber Number
highlight default link zenAttribute PreProc
highlight default link zenOperator Operator

let b:current_syntax = "zen"
`

// tmTemplate is the TextMate grammar template. The four %s verbs are, in
// order: the keywords alternation, the booleans alternation, the scalar
// type alternation, and the labels+verbs alternation (verbs are embedded in
// the labels rule, matching the reference grammar shape that
// editors/parity_test.go also accepts).
const tmTemplate = `{
  "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
  "name": "Zen",
  "scopeName": "source.zen",
  "patterns": [
    { "include": "#comments" },
    { "include": "#strings" },
    { "include": "#numbers" },
    { "include": "#keywords" },
    { "include": "#booleans" },
    { "include": "#types" },
    { "include": "#labels" },
    { "include": "#attributes" },
    { "include": "#operators" },
    { "include": "#punctuation" }
  ],
  "repository": {
    "comments": {
      "patterns": [
        {
          "name": "comment.line.double-slash.zen",
          "match": "//.*$"
        }
      ]
    },
    "strings": {
      "name": "string.quoted.double.zen",
      "begin": "\"",
      "end": "\"",
      "patterns": [
        {
          "name": "constant.character.escape.zen",
          "match": "\\\\."
        }
      ]
    },
    "numbers": {
      "patterns": [
        {
          "name": "constant.numeric.duration.zen",
          "match": "\\b\\d+(ns|us|µs|ms|s|m|h)\\b"
        },
        {
          "name": "constant.numeric.zen",
          "match": "\\b\\d+(\\.\\d+)?\\b"
        }
      ]
    },
    "keywords": {
      "name": "keyword.control.zen",
      "match": "\\b(%s)\\b"
    },
    "booleans": {
      "name": "constant.language.boolean.zen",
      "match": "\\b(%s)\\b"
    },
    "types": {
      "name": "support.type.zen",
      "match": "\\b(%s)\\b"
    },
    "labels": {
      "name": "variable.parameter.zen",
      "match": "\\b(%s)\\b"
    },
    "attributes": {
      "name": "entity.other.attribute-name.zen",
      "match": "@\\w+"
    },
    "operators": {
      "name": "keyword.operator.zen",
      "match": "->"
    },
    "punctuation": {
      "patterns": [
        {
          "name": "punctuation.definition.tag.zen",
          "match": "[{}()]"
        }
      ]
    }
  }
}
`
