package gogen

import (
	"fmt"
	"strings"

	"github.com/zenta-dev/zever/internal/dsl/ir"
)

// stubHeader deliberately does NOT say "DO NOT EDIT" -- unlike every other
// gogen output, a stub is written once (GenerateServiceStub is never part of
// Generate's always-overwritten output map) and is meant to be filled in by
// hand.
const stubHeader = "// Code generated by the zever DSL gogen backend as a starting point.\n" +
	"// Fill in the real business logic below -- this file is written once and\n" +
	"// never regenerated, so it is safe to edit freely.\n\n"

// GenerateServiceStub renders a compiling, unimplemented starting-point
// implementation of svc's generated Service interface: a "<Service>Impl"
// struct, a compile-time assertion that it satisfies "<genAlias>.<Service>",
// and one method per operation returning apperror.New(apperror.Unimplemented,
// ...). pkg names the package the stub file itself belongs to; genAlias and
// genImportPath name the already-generated gogen package (service.go's
// "<Service>" interface, types.go's request/response aliases) the stub
// implements against, so the caller is free to place the stub in any
// directory/package outside the always-regenerated gogen output -- typically
// "internal/app/<module>/<service_snake>.go".
//
// GenerateServiceStub is a separate, exported entry point rather than an
// addition to Generate's output map: a stub is the opposite regeneration
// contract from every other gogen file -- it must never be silently
// clobbered once a developer starts filling it in. Callers are responsible
// for the skip-if-exists check before writing the result to disk.
func GenerateServiceStub(pkg, genAlias, genImportPath string, svc *ir.Service) ([]byte, error) {
	sm := newServiceModel(svc)

	var body strings.Builder

	implName := sm.Name + "Impl"

	fmt.Fprintf(&body, "// %s is a starting-point implementation of %s. Every method below\n", implName, sm.Name)
	body.WriteString("// currently returns apperror.Unimplemented -- replace each body with real\n")
	body.WriteString("// business logic.\n")
	fmt.Fprintf(&body, "type %s struct{}\n\n", implName)
	fmt.Fprintf(&body, "var _ %s.%s = (*%s)(nil)\n\n", genAlias, sm.Name, implName)
	fmt.Fprintf(&body, "// New%s constructs a %s.\n", implName, implName)
	fmt.Fprintf(&body, "func New%s() *%s {\n\treturn &%s{}\n}\n", implName, implName, implName)

	for _, op := range sm.Operations {
		body.WriteString("\n")

		if op.Paginated {
			fmt.Fprintf(&body, "func (s *%s) %s(ctx context.Context, req *%s.%s, cursor string, limit int32) (*%s.%s, error) {\n",
				implName, op.Name, genAlias, op.RequestType, genAlias, op.ReturnType)
		} else {
			fmt.Fprintf(&body, "func (s *%s) %s(ctx context.Context, req *%s.%s) (*%s.%s, error) {\n",
				implName, op.Name, genAlias, op.RequestType, genAlias, op.ReturnType)
		}

		fmt.Fprintf(&body, "\treturn nil, apperror.New(apperror.Unimplemented, %q)\n", op.Name+" not implemented")
		body.WriteString("}\n")
	}

	var b strings.Builder

	b.WriteString(stubHeader)
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("import (\n")
	fmt.Fprintf(&b, "\t%q\n\n", importContext)
	fmt.Fprintf(&b, "\t%q\n", pkgApperror)
	fmt.Fprintf(&b, "\t%s %q\n", genAlias, genImportPath)
	b.WriteString(")\n\n")
	b.WriteString(body.String())

	return formatSource(b.String())
}
