package gogen

import (
	"fmt"
	"go/format"
	"strings"
)

// formatSource runs src through go/format.Source, normalizing spacing and
// catching syntactically invalid Go emission before it ever reaches a
// caller. This only parses and re-prints syntax -- it never resolves
// imported packages.
func formatSource(src string) ([]byte, error) {
	return format.Source([]byte(src))
}

const generatedHeader = "// Code generated by the zever DSL gogen backend. DO NOT EDIT.\n\n"

// renderModuleFiles renders all five always-regenerated files for one
// module and returns them keyed by their output-relative path. The per-file
// renderers are infallible (they only assemble strings), so the only failure
// is go/format rejecting the emission -- kept as an error return so a
// hostile model can never silently produce uncompilable output.
func renderModuleFiles(pkg, dir string, data moduleModel) (map[string][]byte, error) {
	files := map[string]func() string{
		dir + "/types.go":    func() string { return renderTypes(pkg, data) },
		dir + "/service.go":  func() string { return renderService(pkg, data) },
		dir + "/router.go":   func() string { return renderRouter(pkg, data) },
		dir + "/grpc.go":     func() string { return renderGRPC(pkg, data) },
		dir + "/register.go": func() string { return renderRegister(pkg, data) },
	}

	out := make(map[string][]byte, len(files))

	// Render and format in a fixed order so any formatting error is reported
	// deterministically rather than depending on map iteration order.
	for _, path := range []string{dir + "/types.go", dir + "/service.go", dir + "/router.go", dir + "/grpc.go", dir + "/register.go"} {
		src := files[path]()

		formatted, err := formatSource(src)
		if err != nil {
			return nil, fmt.Errorf("format %s: %w\n--- source ---\n%s", path, err, src)
		}

		out[path] = formatted
	}

	return out, nil
}

// renderTypes renders "<module>/types.go": one Go type ALIAS per distinct
// request type and per distinct returned type (an entity, or a paginated
// operation's synthesized "<Op>Response" wrapper) this module's operations
// use, each aliasing the real protobuf message type protogogen generates
// for the identical schema (same module/service/operation names -- the two
// backends are built to agree). These are declared with "=" (a genuine type
// alias, not a new named type): every method the aliased protobuf type has
// -- proto.Message, protojson (un)marshaling, generated field getters -- is
// available through the alias unchanged, which is what lets router.go and
// grpc.go use these local names interchangeably with protogogen's own
// generated types. No plain struct is ever emitted here.
func renderTypes(pkg string, data moduleModel) string {
	var body strings.Builder

	seen := map[string]bool{}

	writeAlias := func(name, comment string) {
		if seen[name] {
			return
		}

		seen[name] = true

		fmt.Fprintf(&body, "// %s is a type alias for the real protobuf message %s.%s.\n", name, data.PBAlias, comment)
		fmt.Fprintf(&body, "type %s = %s.%s\n\n", name, data.PBAlias, comment)
	}

	for _, svc := range data.Services {
		for _, op := range svc.Operations {
			writeAlias(op.RequestType, op.RequestType)

			if op.Paginated {
				writeAlias(op.ReturnType, op.ReturnType)
			} else {
				writeAlias(op.ItemType, op.ItemType)
			}

			for _, p := range op.Params {
				if p.EnumName != "" {
					writeAlias(p.GoType, p.GoType)
				}
			}
		}
	}

	var b strings.Builder

	b.WriteString(generatedHeader)
	fmt.Fprintf(&b, "// Package %s holds the generated type aliases mapping this module's\n", pkg)
	b.WriteString("// request/response types onto the real protobuf message types protogogen\n")
	fmt.Fprintf(&b, "// generates for the %s module's services.\n", pkg)
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("import (\n")
	fmt.Fprintf(&b, "\t%s %q\n", data.PBAlias, data.PBImportPath)
	b.WriteString(")\n\n")
	b.WriteString(body.String())

	return b.String()
}
