package zenorm

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/zenta-dev/zever/internal/dsl/ir"
	"github.com/zenta-dev/zever/internal/dsl/naming"
)

const (
	importFmt  = "fmt"
	importTime = "time"
	importOrm  = "github.com/zenta-dev/zever/orm"
)

// formatSource runs src through go/format.Source, normalizing spacing and
// catching syntactically invalid Go emission before it ever reaches a
// golden file.
func formatSource(src string) ([]byte, error) {
	return format.Source([]byte(src))
}

// importSet accumulates the imports of every entity in one module file,
// de-duplicated across them.
type importSet struct {
	std map[string]bool
}

func newImportSet() *importSet {
	return &importSet{std: map[string]bool{importFmt: true}}
}

func (s *importSet) add(m entityModel) {
	for _, f := range m.Fields {
		if f.Import != "" {
			s.std[f.Import] = true
		}
	}
}

func writeImports(b *strings.Builder, s *importSet) {
	b.WriteString("import (\n")

	paths := make([]string, 0, len(s.std))
	for p := range s.std {
		paths = append(paths, p)
	}

	sort.Strings(paths)

	for _, p := range paths {
		fmt.Fprintf(b, "\t%q\n", p)
	}

	b.WriteString("\n")
	fmt.Fprintf(b, "\t%q\n", importOrm)
	b.WriteString(")\n\n")
}

// renderModuleFile renders every entity of one ir.Module into a single Go
// source file: one package clause, one de-duplicated import block, the
// named-enum declarations the module's entities reference, then each
// entity's generated Table/Cols/struct/Scan/Columns section in declaration
// order. enums carries the schema-wide named-enum index so a field
// referencing an enum declared in another module still resolves its values
// (named enums are global).
func renderModuleFile(m *ir.Module, enums map[string]*ir.Enum) (path string, content []byte, err error) {
	pkg, path := moduleNaming(m)

	imports := newImportSet()

	var body strings.Builder

	for i, e := range m.Entities {
		if i > 0 {
			body.WriteString("\n")
		}

		em, emErr := newEntityModel(e)
		if emErr != nil {
			return "", nil, emErr
		}

		imports.add(em)
		renderEntityBody(&body, em, e.Name)
	}

	var b strings.Builder

	b.WriteString("// Code generated by the zever DSL zenorm backend. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "// Package %s holds the generated orm query-builder types for the %s\n", pkg, pascalModuleLabel(moduleLabel(m)))
	b.WriteString("// module's entities.\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	writeImports(&b, imports)
	renderEnumDecls(&b, m, enums)
	b.WriteString(body.String())

	formatted, fmtErr := formatSource(b.String())
	if fmtErr != nil {
		return "", nil, fmt.Errorf("zenorm: module %s: %w", moduleLabel(m), fmtErr)
	}

	return path, formatted, nil
}

// renderEnumDecls emits one string-kind Go type plus typed constants per
// named enum the module's entities reference, in first-reference order.
// Without these, goScalar's PascalCase named-enum mapping would reference
// Go types no file defines and the generated package would not compile.
// The definitions are plain string kinds (not database/sql Valuer/Scanner
// implementations) on purpose: database/sql converts string-kind values
// and destinations through its standard reflection paths, so the type
// round-trips through every driver unchanged.
func renderEnumDecls(b *strings.Builder, m *ir.Module, enums map[string]*ir.Enum) {
	seen := map[string]bool{}

	for _, e := range m.Entities {
		for _, f := range e.Fields {
			if f.Type.Scalar != ir.TEnum || f.Type.EnumName == "" {
				continue
			}

			name := f.Type.EnumName
			if seen[name] {
				continue
			}

			seen[name] = true

			enum, ok := enums[name]
			if !ok || enum == nil {
				continue
			}

			goType := naming.PascalCase(name)
			fmt.Fprintf(b, "// %s is the Go type for the %q enum declared in the schema.\n", goType, name)
			fmt.Fprintf(b, "type %s string\n\n", goType)

			fmt.Fprintf(b, "// %s values.\n", goType)
			b.WriteString("const (\n")
			for _, v := range enum.Values {
				fmt.Fprintf(b, "\t%s%s %s = %q\n", goType, goName(v), goType, v)
			}
			b.WriteString(")\n\n")
		}
	}
}

// moduleLabel names a module for doc comments and error messages,
// standing in a readable phrase for the implicit unnamed module.
func moduleLabel(m *ir.Module) string {
	if m == nil || m.Name == "" {
		return ""
	}

	return m.Name
}
