package zenorm

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/zenta-dev/zever/internal/dsl/ir"
)

const (
	importFmt  = "fmt"
	importTime = "time"
	importJSON = "encoding/json"
	importOrm  = "github.com/zenta-dev/zever/orm"
)

// formatSource runs src through go/format.Source, normalizing spacing and
// catching syntactically invalid Go emission before it ever reaches a
// golden file.
func formatSource(src string) ([]byte, error) {
	return format.Source([]byte(src))
}

// importSet accumulates the imports of every entity in one module file,
// de-duplicated across them.
type importSet struct {
	std map[string]bool
}

func newImportSet() *importSet {
	return &importSet{std: map[string]bool{importFmt: true}}
}

func (s *importSet) add(m entityModel) {
	for _, f := range m.Fields {
		if f.Import != "" {
			s.std[f.Import] = true
		}
	}
}

func writeImports(b *strings.Builder, s *importSet) {
	b.WriteString("import (\n")

	paths := make([]string, 0, len(s.std))
	for p := range s.std {
		paths = append(paths, p)
	}

	sort.Strings(paths)

	for _, p := range paths {
		fmt.Fprintf(b, "\t%q\n", p)
	}

	b.WriteString("\n")
	fmt.Fprintf(b, "\t%q\n", importOrm)
	b.WriteString(")\n\n")
}

// renderModuleFile renders every entity of one ir.Module into a single Go
// source file: one package clause, one de-duplicated import block, then
// each entity's generated Table/Cols/struct/Scan/Columns section in
// declaration order.
func renderModuleFile(m *ir.Module) (path string, content []byte, err error) {
	pkg, path := moduleNaming(m)

	imports := newImportSet()

	var body strings.Builder

	for i, e := range m.Entities {
		if i > 0 {
			body.WriteString("\n")
		}

		em, emErr := newEntityModel(e)
		if emErr != nil {
			return "", nil, emErr
		}

		imports.add(em)
		renderEntityBody(&body, em, e.Name)
	}

	var b strings.Builder

	b.WriteString("// Code generated by the zever DSL zenorm backend. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "// Package %s holds the generated orm query-builder types for the %s\n", pkg, pascalModuleLabel(moduleLabel(m)))
	b.WriteString("// module's entities.\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	writeImports(&b, imports)
	b.WriteString(body.String())

	formatted, fmtErr := formatSource(b.String())
	if fmtErr != nil {
		return "", nil, fmt.Errorf("zenorm: module %s: %w", moduleLabel(m), fmtErr)
	}

	return path, formatted, nil
}

// moduleLabel names a module for doc comments and error messages,
// standing in a readable phrase for the implicit unnamed module.
func moduleLabel(m *ir.Module) string {
	if m == nil || m.Name == "" {
		return ""
	}

	return m.Name
}
