package mcp

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"go/parser"
	"go/token"
	"sort"
	"strings"

	"github.com/zenta-dev/zever/dsl/ir"
)

// renderServerModule renders a runnable MCP stdio server (package main) for
// one module's services. The server embeds the module's tool manifests,
// dispatches tools/call to per-tool handler stubs, and speaks
// newline-delimited JSON-RPC 2.0 on stdin/stdout. It depends only on the
// standard library. Handler stubs return a not-implemented error for the
// developer to fill in.
func renderServerModule(m *ir.Module, services []serviceManifest) ([]byte, error) {
	manifest, err := marshalServices(services)
	if err != nil {
		return nil, err
	}

	var b strings.Builder

	b.WriteString("// Code generated by zever compile --backend mcp. DO NOT EDIT.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"io\"\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString(")\n\n")

	fmt.Fprintf(&b, "const manifestJSON = %q\n\n", manifest)

	b.WriteString("type toolHandler func(ctx context.Context, args map[string]any) (string, error)\n\n")

	names := collectToolNames(services)
	for _, name := range names {
		fmt.Fprintf(&b, "func handle%s(ctx context.Context, args map[string]any) (string, error) {\n", name)
		fmt.Fprintf(&b, "\treturn \"\", fmt.Errorf(\"not implemented: %s\")\n", name)
		b.WriteString("}\n\n")
	}

	b.WriteString("var mcpHandlers = map[string]toolHandler{\n")
	for _, name := range names {
		fmt.Fprintf(&b, "\t%q: handle%s,\n", name, name)
	}
	b.WriteString("}\n\n")

	b.WriteString(serverLoopSource)

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("mcp: format server source: %w", err)
	}

	if _, err := parser.ParseFile(token.NewFileSet(), "main.go", formatted, parser.AllErrors); err != nil {
		return nil, fmt.Errorf("mcp: parse server source: %w", err)
	}

	return formatted, nil
}

// marshalServices encodes services as compact JSON for embedding.
func marshalServices(services []serviceManifest) (string, error) {
	var buf bytes.Buffer

	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)

	if err := enc.Encode(services); err != nil {
		return "", err
	}

	return strings.TrimSpace(buf.String()), nil
}

// collectToolNames returns every tool name across services in sorted order
// for deterministic output.
func collectToolNames(services []serviceManifest) []string {
	var names []string

	for _, svc := range services {
		for _, tool := range svc.Tools {
			names = append(names, tool.Name)
		}
	}

	sort.Strings(names)

	return names
}

// serverLoopSource is the fixed stdio JSON-RPC dispatch loop emitted into
// every generated server. Tool schemas come from manifestJSON; execution
// delegates to mcpHandlers.
const serverLoopSource = `type rpcRequest struct {
	JSONRPC string          ` + "`json:\"jsonrpc\"`" + `
	ID      json.RawMessage ` + "`json:\"id,omitempty\"`" + `
	Method  string          ` + "`json:\"method\"`" + `
	Params  json.RawMessage ` + "`json:\"params,omitempty\"`" + `
}

type rpcResponse struct {
	JSONRPC string          ` + "`json:\"jsonrpc\"`" + `
	ID      json.RawMessage ` + "`json:\"id,omitempty\"`" + `
	Result  any             ` + "`json:\"result,omitempty\"`" + `
	Error   *rpcError       ` + "`json:\"error,omitempty\"`" + `
}

type rpcError struct {
	Code    int    ` + "`json:\"code\"`" + `
	Message string ` + "`json:\"message\"`" + `
}

type textContent struct {
	Type string ` + "`json:\"type\"`" + `
	Text string ` + "`json:\"text\"`" + `
}

type callToolResult struct {
	Content []textContent ` + "`json:\"content\"`" + `
	IsError bool          ` + "`json:\"isError,omitempty\"`" + `
}

type callParams struct {
	Name      string         ` + "`json:\"name\"`" + `
	Arguments map[string]any ` + "`json:\"arguments\"`" + `
}

type manifestTool struct {
	Name         string         ` + "`json:\"name\"`" + `
	Description  string         ` + "`json:\"description,omitempty\"`" + `
	InputSchema  map[string]any ` + "`json:\"inputSchema\"`" + `
	OutputSchema map[string]any ` + "`json:\"outputSchema,omitempty\"`" + `
}

type manifestService struct {
	Service     string                  ` + "`json:\"service\"`" + `
	Module      string                  ` + "`json:\"module\"`" + `
	Tools       []manifestTool          ` + "`json:\"tools\"`" + `
	Definitions map[string]any          ` + "`json:\"definitions,omitempty\"`" + `
}

func loadManifest() ([]manifestService, error) {
	var services []manifestService
	if err := json.Unmarshal([]byte(manifestJSON), &services); err != nil {
		return nil, err
	}
	return services, nil
}

func main() {
	if err := run(context.Background(), os.Stdin, os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(ctx context.Context, in io.Reader, out io.Writer) error {
	services, err := loadManifest()
	if err != nil {
		return err
	}

	dec := json.NewDecoder(in)
	enc := json.NewEncoder(out)

	for {
		var req rpcRequest
		if err := dec.Decode(&req); err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}

		if len(req.ID) == 0 {
			continue
		}

		if err := enc.Encode(handle(ctx, req, services)); err != nil {
			return err
		}
	}
}

func handle(ctx context.Context, req rpcRequest, services []manifestService) rpcResponse {
	switch req.Method {
	case "initialize":
		return rpcResponse{JSONRPC: "2.0", ID: req.ID, Result: map[string]any{
			"protocolVersion": "2024-11-05",
			"capabilities":    map[string]any{"tools": map[string]any{}},
			"serverInfo":      map[string]any{"name": "zever-mcp-server", "version": "0.0.0"},
		}}
	case "ping":
		return rpcResponse{JSONRPC: "2.0", ID: req.ID, Result: map[string]any{}}
	case "tools/list":
		tools := []map[string]any{}
		for _, svc := range services {
			for _, tool := range svc.Tools {
				tools = append(tools, map[string]any{
					"name":        tool.Name,
					"description": tool.Description,
					"inputSchema": tool.InputSchema,
				})
			}
		}
		return rpcResponse{JSONRPC: "2.0", ID: req.ID, Result: map[string]any{"tools": tools}}
	case "tools/call":
		return callTool(ctx, req)
	default:
		return rpcResponse{JSONRPC: "2.0", ID: req.ID, Error: &rpcError{Code: -32601, Message: "method not found: " + req.Method}}
	}
}

func callTool(ctx context.Context, req rpcRequest) rpcResponse {
	var p callParams
	if err := json.Unmarshal(req.Params, &p); err != nil {
		return rpcResponse{JSONRPC: "2.0", ID: req.ID, Error: &rpcError{Code: -32602, Message: "invalid tools/call params"}}
	}

	h, ok := mcpHandlers[p.Name]
	if !ok {
		return rpcResponse{JSONRPC: "2.0", ID: req.ID, Error: &rpcError{Code: -32602, Message: "unknown tool: " + p.Name}}
	}

	text, err := h(ctx, p.Arguments)
	if err != nil {
		return rpcResponse{JSONRPC: "2.0", ID: req.ID, Result: callToolResult{
			Content: []textContent{{Type: "text", Text: err.Error()}},
			IsError: true,
		}}
	}

	return rpcResponse{JSONRPC: "2.0", ID: req.ID, Result: callToolResult{
		Content: []textContent{{Type: "text", Text: text}},
	}}
}
`
