// Command tinker-shim is the per-project backend for `zever tinker`.
//
// Code generated by "zever generate tinker". Safe to edit: regenerate with
// --force to discard local changes.
//
// It builds this project's real container and answers a fixed set of verbs
// over a line-delimited JSON protocol: one request per line on stdin, one
// framed response per line on stdout. `zever tinker` spawns it with
// `go run` and binds db/cache/queue/job values in a yaegi REPL that
// call these verbs.
//
// Run it by hand to poke at the protocol:
//
//	echo '{"verb":"ping"}' | go run ./cmd/tinker-shim
package main

import (
	"bufio"
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"reflect"
	"time"
	"unsafe"

	"github.com/zenta-dev/zever/container"
	"github.com/zenta-dev/zever/core/db"
)

// framePrefix marks a stdout line as a protocol response, so that anything
// else the process writes to stdout (an app logger, for instance) is not
// mistaken for protocol traffic.
//
// MUST STAY IN SYNC WITH cmd/zever/tinker_protocol.go in github.com/zenta-dev/zever.
const framePrefix = `@@zever-tinker@@`

// --- wire protocol ----------------------------------------------------
//
// MUST STAY IN SYNC WITH cmd/zever/tinker_protocol.go in github.com/zenta-dev/zever.
// These declarations are duplicated rather than imported because this shim is
// compiled inside this project's module, which cannot reach zever's
// cmd/zever package.

type tinkerRequest struct {
	Verb string          `json:"verb"`
	Args json.RawMessage `json:"args,omitempty"`
}

type tinkerResponse struct {
	Result json.RawMessage `json:"result,omitempty"`
	Error  string          `json:"error,omitempty"`
}

type dbQueryArgs struct {
	SQL  string `json:"sql"`
	Args []any  `json:"args,omitempty"`
}

type dbQueryResult struct {
	Columns []string `json:"columns"`
	Rows    [][]any  `json:"rows"`
}

type dbExecArgs struct {
	SQL  string `json:"sql"`
	Args []any  `json:"args,omitempty"`
}

type dbExecResult struct {
	RowsAffected int64 `json:"rows_affected"`
}

type cacheGetArgs struct {
	Key string `json:"key"`
}

type cacheGetResult struct {
	Value string `json:"value"`
}

type cacheSetArgs struct {
	Key        string `json:"key"`
	Value      string `json:"value"`
	TTLSeconds int    `json:"ttl_seconds,omitempty"`
}

type cacheDeleteArgs struct {
	Key string `json:"key"`
}

type cacheExistsArgs struct {
	Key string `json:"key"`
}

type boolResult struct {
	Value bool `json:"value"`
}

type queuePushArgs struct {
	Topic   string            `json:"topic"`
	Payload string            `json:"payload"`
	Headers map[string]string `json:"headers,omitempty"`
}

type queueLengthArgs struct {
	Topic string `json:"topic"`
}

type int64Result struct {
	Value int64 `json:"value"`
}

type jobDispatchArgs struct {
	Name string          `json:"name"`
	Args json.RawMessage `json:"args,omitempty"`
}

// --- shim -------------------------------------------------------------

func main() {
	if err := run(); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, "tinker-shim:", err)
		os.Exit(1)
	}
}

func run() error {
	c := container.New(nil)

	ctx := context.Background()
	defer func() { _ = c.Close(ctx) }()

	out := bufio.NewWriter(os.Stdout)
	defer func() { _ = out.Flush() }()

	in := bufio.NewScanner(os.Stdin)
	in.Buffer(make([]byte, 0, 64*1024), 16*1024*1024)

	for in.Scan() {
		line := in.Bytes()
		if len(line) == 0 {
			continue
		}

		resp := handleLine(ctx, c, line)

		payload, merr := json.Marshal(resp)
		if merr != nil {
			payload = []byte(`{"error":"tinker-shim: marshal response failed"}`)
		}

		if _, werr := out.WriteString(framePrefix); werr != nil {
			return fmt.Errorf("write response: %w", werr)
		}

		if _, werr := out.Write(payload); werr != nil {
			return fmt.Errorf("write response: %w", werr)
		}

		if werr := out.WriteByte('\n'); werr != nil {
			return fmt.Errorf("write response: %w", werr)
		}

		if ferr := out.Flush(); ferr != nil {
			return fmt.Errorf("flush response: %w", ferr)
		}
	}

	if serr := in.Err(); serr != nil {
		return fmt.Errorf("read request: %w", serr)
	}

	return nil
}

// handleLine never returns an error and never panics: a malformed line or an
// unknown verb becomes an error response so the REPL on the other end stays
// usable.
func handleLine(ctx context.Context, c *container.Container, line []byte) tinkerResponse {
	var req tinkerRequest
	if err := json.Unmarshal(line, &req); err != nil {
		return errResponse(fmt.Errorf("malformed request: %w", err))
	}

	result, err := dispatch(ctx, c, req)
	if err != nil {
		return errResponse(err)
	}

	if result == nil {
		return tinkerResponse{}
	}

	payload, err := json.Marshal(result)
	if err != nil {
		return errResponse(fmt.Errorf("marshal result for %q: %w", req.Verb, err))
	}

	return tinkerResponse{Result: payload}
}

func errResponse(err error) tinkerResponse {
	return tinkerResponse{Error: err.Error()}
}

//nolint:cyclop,funlen // a flat verb switch is the clearest shape here
func dispatch(ctx context.Context, c *container.Container, req tinkerRequest) (any, error) {
	switch req.Verb {
	case "ping":
		return "pong", nil

	case "db.query":
		var a dbQueryArgs
		if err := decodeArgs(req, &a); err != nil {
			return nil, err
		}

		handle, err := c.DB()
		if err != nil {
			return nil, err
		}

		return queryRows(ctx, handle, a)

	case "db.exec":
		var a dbExecArgs
		if err := decodeArgs(req, &a); err != nil {
			return nil, err
		}

		handle, err := c.DB()
		if err != nil {
			return nil, err
		}

		n, err := handle.Exec(ctx, a.SQL, a.Args...)
		if err != nil {
			return nil, err
		}

		return dbExecResult{RowsAffected: n}, nil

	case "cache.get":
		var a cacheGetArgs
		if err := decodeArgs(req, &a); err != nil {
			return nil, err
		}

		ch, err := c.Cache()
		if err != nil {
			return nil, err
		}

		v, err := ch.Get(ctx, a.Key)
		if err != nil {
			return nil, err
		}

		return cacheGetResult{Value: string(v)}, nil

	case "cache.set":
		var a cacheSetArgs
		if err := decodeArgs(req, &a); err != nil {
			return nil, err
		}

		ch, err := c.Cache()
		if err != nil {
			return nil, err
		}

		var ttl time.Duration
		if a.TTLSeconds > 0 {
			ttl = time.Duration(a.TTLSeconds) * time.Second
		}

		return nil, ch.Set(ctx, a.Key, []byte(a.Value), ttl)

	case "cache.delete":
		var a cacheDeleteArgs
		if err := decodeArgs(req, &a); err != nil {
			return nil, err
		}

		ch, err := c.Cache()
		if err != nil {
			return nil, err
		}

		return nil, ch.Delete(ctx, a.Key)

	case "cache.exists":
		var a cacheExistsArgs
		if err := decodeArgs(req, &a); err != nil {
			return nil, err
		}

		ch, err := c.Cache()
		if err != nil {
			return nil, err
		}

		ok, err := ch.Exists(ctx, a.Key)
		if err != nil {
			return nil, err
		}

		return boolResult{Value: ok}, nil

	case "queue.push":
		var a queuePushArgs
		if err := decodeArgs(req, &a); err != nil {
			return nil, err
		}

		q, err := c.Queue()
		if err != nil {
			return nil, err
		}

		return nil, q.Push(ctx, a.Topic, []byte(a.Payload), a.Headers)

	case "queue.length":
		var a queueLengthArgs
		if err := decodeArgs(req, &a); err != nil {
			return nil, err
		}

		q, err := c.Queue()
		if err != nil {
			return nil, err
		}

		n, err := q.Length(ctx, a.Topic)
		if err != nil {
			return nil, err
		}

		return int64Result{Value: n}, nil

	case "job.dispatch":
		var a jobDispatchArgs
		if err := decodeArgs(req, &a); err != nil {
			return nil, err
		}

		d, err := c.Job()
		if err != nil {
			return nil, err
		}

		var jobArgs any
		if len(a.Args) > 0 {
			if err := json.Unmarshal(a.Args, &jobArgs); err != nil {
				return nil, fmt.Errorf("job.dispatch: decode args: %w", err)
			}
		}

		return nil, d.Dispatch(ctx, a.Name, jobArgs)

	default:
		return nil, fmt.Errorf("unknown verb %q", req.Verb)
	}
}

func decodeArgs(req tinkerRequest, dst any) error {
	if len(req.Args) == 0 {
		return nil
	}

	if err := json.Unmarshal(req.Args, dst); err != nil {
		return fmt.Errorf("%s: decode args: %w", req.Verb, err)
	}

	return nil
}

func queryRows(ctx context.Context, handle db.DB, a dbQueryArgs) (dbQueryResult, error) {
	rows, err := handle.Query(ctx, a.SQL, a.Args...)
	if err != nil {
		return dbQueryResult{}, err
	}

	defer func() { _ = rows.Close() }()

	cols := columnNames(rows)
	if len(cols) == 0 {
		return dbQueryResult{}, errors.New("db.query: cannot determine result columns for this db adapter")
	}

	out := dbQueryResult{Columns: cols, Rows: [][]any{}}

	for rows.Next() {
		vals := make([]any, len(cols))

		ptrs := make([]any, len(cols))
		for i := range vals {
			ptrs[i] = &vals[i]
		}

		if err := rows.Scan(ptrs...); err != nil {
			return dbQueryResult{}, err
		}

		for i, v := range vals {
			if b, ok := v.([]byte); ok {
				vals[i] = string(b)
			}
		}

		out.Rows = append(out.Rows, vals)
	}

	if err := rows.Err(); err != nil {
		return dbQueryResult{}, err
	}

	return out, nil
}

// columnNames recovers the result column names from a db.Rows. The db.Rows
// interface now declares Columns(), so the direct assertion is the fast
// path; the reflection probe below covers wrapped *sql.Rows the stock
// adapters may still hide behind.
func columnNames(rows db.Rows) []string {
	type columner interface{ Columns() ([]string, error) }

	if c, ok := rows.(columner); ok {
		if cols, err := c.Columns(); err == nil {
			return cols
		}
	}

	rv := reflect.ValueOf(rows)
	if rv.Kind() != reflect.Pointer || rv.IsNil() {
		return nil
	}

	elem := rv.Elem()
	if elem.Kind() != reflect.Struct {
		return nil
	}

	for _, name := range []string{"rows", "Rows"} {
		fld := elem.FieldByName(name)
		if !fld.IsValid() {
			continue
		}

		inner := fieldValue(fld)
		if inner == nil {
			continue
		}

		if c, ok := inner.(columner); ok {
			if cols, err := c.Columns(); err == nil {
				return cols
			}
		}

		if sr, ok := inner.(*sql.Rows); ok {
			if cols, err := sr.Columns(); err == nil {
				return cols
			}
		}
	}

	return nil
}

func fieldValue(fld reflect.Value) any {
	if fld.CanInterface() {
		return fld.Interface()
	}

	if !fld.CanAddr() {
		return nil
	}

	//nolint:gosec // reading an unexported field of an adapter we own
	return reflect.NewAt(fld.Type(), unsafe.Pointer(fld.UnsafeAddr())).Elem().Interface()
}
