package proto

import (
	"fmt"
	"strings"

	"github.com/zenta-dev/zever/internal/dsl/ir"
	"github.com/zenta-dev/zever/internal/dsl/naming"
)

// Well-known and external import paths a rendered module file may need.
const (
	importTimestamp   = "google/protobuf/timestamp.proto"
	importStruct      = "google/protobuf/struct.proto"
	importHTTP        = "google/api/annotations.proto"
	importAnnotations = "zengo/annotations.proto"
)

// fileCtx accumulates the set of imports a single module's rendered file
// needs, discovered while rendering its messages and services. Imports are
// only emitted for a module's file when something in that file actually
// uses them (design doc: "External imports ... are only emitted per-file
// when actually used by that module").
type fileCtx struct {
	imports map[string]bool

	// messageNames tracks every top-level message/enum-scoped identifier
	// this backend has emitted so far into the current module file — entity
	// message names and, per RPC, its synthesized "<Name>Request" message
	// name — so a second emission of the same name can be reported as a
	// real collision instead of silently producing invalid duplicate-message
	// proto output. Each value names the RPC/entity that first claimed it,
	// used to build a clear "colliding with X" diagnostic.
	messageNames map[string]string
}

func newFileCtx() *fileCtx {
	return &fileCtx{imports: map[string]bool{}, messageNames: map[string]string{}}
}

func (c *fileCtx) require(importPath string) {
	if importPath != "" {
		c.imports[importPath] = true
	}
}

// claimMessageName records that owner (e.g. "entity Order" or "rpc
// OrderService.Get") is emitting proto message name, returning an error
// naming both the current and the prior owner if name was already claimed
// by something else in this file.
func (c *fileCtx) claimMessageName(name, owner string) error {
	if prior, ok := c.messageNames[name]; ok {
		return fmt.Errorf(
			"proto: message name %q generated by %s collides with the one already generated by %s in the same file",
			name, owner, prior)
	}

	c.messageNames[name] = owner

	return nil
}

// moduleNaming returns the package name, go_package option value, and
// output-relative file path for m. The version segment is m.Version when
// the module's schema dir declared one (schema/v1/iam/*.zen -> Version
// "v1"), defaulting to "v1" when it didn't -- every unversioned schema
// (Version == "") therefore keeps generating exactly what it always has.
// The implicit unnamed module maps to package zengo.<version> /
// .../gen/zengo<version>;zengo<version> at "schema.proto"; a named module
// "billing" at version "v1" maps to package zengo.billing.v1 /
// .../gen/zengo/billing;billingv1 at "billing/schema.proto".
func moduleNaming(m *ir.Module) (pkg, goPackage, path string) {
	version := m.Version
	if version == "" {
		version = "v1"
	}

	if m.Name == "" {
		return "zengo." + version,
			fmt.Sprintf("github.com/zenta-dev/zen-go/gen/zengo%s;zengo%s", version, version),
			"schema.proto"
	}

	pkg = fmt.Sprintf("zengo.%s.%s", m.Name, version)
	goPackage = fmt.Sprintf("github.com/zenta-dev/zen-go/gen/zengo/%s;%s%s", m.Name, m.Name, version)
	path = m.Name + "/schema.proto"

	return pkg, goPackage, path
}

// renderModuleFile renders one ir.Module into its output-relative file path
// and rendered Protocol Buffers source, per the v1 hardcoded package/path
// shape documented in the design doc.
func renderModuleFile(m *ir.Module) (path string, content []byte, err error) {
	pkg, goPackage, path := moduleNaming(m)

	ctx := newFileCtx()

	var body strings.Builder

	for i, enum := range m.Enums {
		if i > 0 {
			body.WriteString("\n")
		}

		if err := ctx.claimMessageName(naming.PascalCase(enum.Name), "enum "+enum.Name); err != nil {
			return "", nil, err
		}

		enumSrc, err := renderTopLevelEnum(enum)
		if err != nil {
			return "", nil, err
		}

		body.WriteString(enumSrc)
	}

	for i, e := range m.Entities {
		if i > 0 || len(m.Enums) > 0 {
			body.WriteString("\n")
		}

		if err := renderMessage(&body, e, ctx); err != nil {
			return "", nil, err
		}
	}

	// Messages never emit tables (atlas/zenorm guard) but do emit proto messages.
	for i, msg := range m.Messages {
		if i > 0 || len(m.Entities) > 0 {
			body.WriteString("\n")
		}

		if err := renderMessageForMessage(&body, msg, ctx); err != nil {
			return "", nil, err
		}
	}

	for _, s := range m.Services {
		if body.Len() > 0 {
			body.WriteString("\n")
		}

		if err := renderService(&body, s, ctx); err != nil {
			return "", nil, err
		}
	}

	var header strings.Builder

	header.WriteString("syntax = \"proto3\";\n\n")
	fmt.Fprintf(&header, "package %s;\n\n", pkg)

	for _, imp := range sortedImports(ctx.imports) {
		fmt.Fprintf(&header, "import %q;\n", imp)
	}

	if len(ctx.imports) > 0 {
		header.WriteString("\n")
	}

	fmt.Fprintf(&header, "option go_package = %q;\n", goPackage)

	if body.Len() > 0 {
		header.WriteString("\n")
	}

	header.WriteString(body.String())

	return path, []byte(header.String()), nil
}

// sortedImports returns imports in a fixed, deterministic order: the two
// well-known-type imports first (timestamp, then struct), then the two
// annotation imports (google/api/annotations.proto, then
// zengo/annotations.proto) — never both a stable sort of arbitrary map keys
// and never alphabetical, so output stays byte-for-byte reproducible and
// reads in "standard types before extension types" order.
func sortedImports(imports map[string]bool) []string {
	order := []string{importTimestamp, importStruct, importHTTP, importAnnotations}

	out := make([]string, 0, len(imports))

	for _, imp := range order {
		if imports[imp] {
			out = append(out, imp)
		}
	}

	return out
}

// renderMessage renders one entity as a proto message: its fields (relations
// are excluded entirely — see the design doc's four-reason rationale) and
// any nested per-field enums.
func renderMessage(w *strings.Builder, e *ir.Entity, ctx *fileCtx) error {
	return renderMessageBody(w, "entity "+e.Name, naming.PascalCase(e.Name), e.Name, e.Fields, ctx)
}

// renderMessageForMessage renders one message as a proto message. Messages
// are scalar-only and never carry relations.
func renderMessageForMessage(w *strings.Builder, m *ir.Message, ctx *fileCtx) error {
	return renderMessageBody(w, "message "+m.Name, naming.PascalCase(m.Name), m.Name, m.Fields, ctx)
}

// renderMessageBody is the shared implementation behind renderMessage and
// renderMessageForMessage: an entity and a message render as identically
// shaped proto messages (fields + nested per-field enums), differing only
// in the owner label used for claimMessageName's collision error and the
// source-decl label used in a field-enum rendering error.
func renderMessageBody(w *strings.Builder, owner, protoName, declName string, fields []*ir.Field, ctx *fileCtx) error {
	if err := ctx.claimMessageName(protoName, owner); err != nil {
		return err
	}

	fmt.Fprintf(w, "message %s {\n", protoName)

	var enums []string

	for i, f := range fields {
		if f.Ref != nil {
			renderRefField(w, f.Name, f.Ref, i+1)
			continue
		}

		renderField(w, f.Name, f.Type, f.Optional, i+1, ctx)

		if f.Type.Scalar == ir.TEnum && f.Type.EnumName == "" {
			enumSrc, err := renderNestedEnum(f.Name, f.Type)
			if err != nil {
				return fmt.Errorf("%s: %w", declName, err)
			}

			enums = append(enums, enumSrc)
		}
	}

	for i, enumSrc := range enums {
		if i == 0 && len(fields) > 0 {
			w.WriteString("\n")
		}

		w.WriteString(enumSrc)
	}

	w.WriteString("}\n")

	return nil
}

// renderField renders one field (an entity field or an RPC/synthesized
// request-message param, both share ir.FieldType) as a single proto field
// declaration at the given 1-based field number. optional emits proto3's
// explicit "optional" field modifier, mirroring the DSL's folded
// optional/nullable field marker (`field: type?`); params never set it,
// since ir.Param carries no such marker.
func renderField(w *strings.Builder, name string, ft ir.FieldType, optional bool, number int, ctx *fileCtx) {
	var typeName string

	if ft.Scalar == ir.TEnum {
		if ft.EnumName != "" {
			typeName = naming.PascalCase(ft.EnumName)
		} else {
			typeName = naming.PascalCase(name) + "Enum"
		}
	} else {
		var importPath string

		typeName, importPath = protoScalar(ft.Scalar)
		ctx.require(importPath)
	}

	prefix := ""
	if optional {
		prefix = "optional "
	}

	fmt.Fprintf(w, "  %s%s %s = %d;\n", prefix, typeName, name, number)
}

// renderRefField renders one RPC param that references an entity/message
// (ref) as a single proto field embedding that type's own generated
// message directly (e.g. "  User user = 1;"), rather than flattening its
// fields into the synthesized request message. The referenced type is
// always rendered into the same per-module file as the synthesized request
// message (module boundary enforcement guarantees same-module usage), so
// no additional import is required.
func renderRefField(w *strings.Builder, name string, ref *ir.TypeRef, number int) {
	fmt.Fprintf(w, "  %s %s = %d;\n", naming.PascalCase(ref.Name()), name, number)
}

// renderNestedEnum renders a field's enum values as a message-nested proto
// enum, following the "PascalCase(field)+Enum" type name and
// "SCREAMING_SNAKE(field)+_UNSPECIFIED = 0" first-value convention. Returns
// an error if two declared enum values normalize to the same
// SCREAMING_SNAKE token (e.g. "inProgress" and "in_progress" both becoming
// "IN_PROGRESS"), which would otherwise silently emit two identical enum
// value names in one nested enum — invalid proto.
func renderNestedEnum(name string, ft ir.FieldType) (string, error) {
	var b strings.Builder

	typeName := naming.PascalCase(name) + "Enum"
	prefix := naming.ScreamingSnake(name)

	fmt.Fprintf(&b, "  enum %s {\n", typeName)
	fmt.Fprintf(&b, "    %s_UNSPECIFIED = 0;\n", prefix)

	seen := make(map[string]string, len(ft.EnumValues))

	for i, v := range ft.EnumValues {
		valueName := prefix + "_" + naming.ScreamingSnake(v)

		if prior, ok := seen[valueName]; ok {
			return "", fmt.Errorf(
				"proto: enum value name %q generated from both %q and %q collide in enum %s",
				valueName, prior, v, typeName)
		}

		seen[valueName] = v

		fmt.Fprintf(&b, "    %s = %d;\n", valueName, i+1)
	}

	b.WriteString("  }\n")

	return b.String(), nil
}

// renderTopLevelEnum renders one named ir.Enum as a top-level proto enum
// (not nested in a message), so every field across every message that
// references it by name shares this single declaration instead of each
// generating its own. Same naming/dedup rules as renderNestedEnum, just
// unindented and file-scoped rather than message-scoped.
//
// Named enums are resolved globally in the DSL (a field in any module may
// reference an enum declared in any other module), but this backend only
// emits the enum's declaration into the .proto file of the module that owns
// it (enum.Module) -- a field in a different module referencing it by name
// works as long as both modules render into the same file (the common,
// single-file-per-module case); a genuine cross-module reference would need
// an explicit proto import, which this backend does not yet generate.
func renderTopLevelEnum(enum *ir.Enum) (string, error) {
	var b strings.Builder

	typeName := naming.PascalCase(enum.Name)
	prefix := naming.ScreamingSnake(enum.Name)

	fmt.Fprintf(&b, "enum %s {\n", typeName)
	fmt.Fprintf(&b, "  %s_UNSPECIFIED = 0;\n", prefix)

	seen := make(map[string]string, len(enum.Values))

	for i, v := range enum.Values {
		valueName := prefix + "_" + naming.ScreamingSnake(v)

		if prior, ok := seen[valueName]; ok {
			return "", fmt.Errorf(
				"proto: enum value name %q generated from both %q and %q collide in enum %s",
				valueName, prior, v, typeName)
		}

		seen[valueName] = v

		fmt.Fprintf(&b, "  %s = %d;\n", valueName, i+1)
	}

	b.WriteString("}\n")

	return b.String(), nil
}

// protoScalar maps a DSL scalar type to its proto type name and, for
// well-known types, the import path that must be present in the file. It
// switches over every ir.ScalarType case explicitly (the exhaustive linter
// is enabled without default-signifies-exhaustive) even though ir.TEnum is
// never actually passed here — enum fields are rendered by renderField via
// renderNestedEnum instead, never through this function.
func protoScalar(t ir.ScalarType) (protoType, importPath string) {
	switch t {
	case ir.TUUID:
		return "string", ""
	case ir.TString:
		return "string", ""
	case ir.TInt32:
		return "int32", ""
	case ir.TInt64:
		return "int64", ""
	case ir.TFloat32:
		return "float", ""
	case ir.TFloat64:
		return "double", ""
	case ir.TBool:
		return "bool", ""
	case ir.TTimestamp:
		return "google.protobuf.Timestamp", importTimestamp
	case ir.TDate:
		return "string", ""
	case ir.TBytes:
		return "bytes", ""
	case ir.TJSON:
		return "google.protobuf.Struct", importStruct
	case ir.TEnum:
		return "", ""
	}

	return "", ""
}
