#!/usr/bin/env bash
# Regenerate .github/dependabot.yml from the go.mod files in the repo.
#
# Layout: ONE gomod entry whose `directories:` lists every module, with a
# `group-by: dependency-name` group. Dependabot then opens a single PR per
# dependency that bumps it in every module that requires it directly,
# instead of one PR per directory (which left sibling modules untidy and
# failed `go mod tidy -diff` in CI). Modules that only carry the bumped
# dependency as `// indirect` (e.g. cmd/zever, examples/*) are reconciled
# by .github/workflows/deps-sync.yml, which runs `make deps-sync` on the PR.
#
# The list is explicit (not a `/**/*` glob) so it matches exactly the
# modules `make tidy-all` / `make deps-sync` see. `make dependabot-check`
# fails when this file is stale (e.g. after adding or removing a module).
#
# Usage: bash tools/gen-dependabot.sh          # rewrite the file
#        bash tools/gen-dependabot.sh --check  # exit 1 if it is stale
set -euo pipefail
cd "$(dirname "$0")/.."

out=".github/dependabot.yml"

render() {
  cat <<'EOF'
# Code generated by tools/gen-dependabot.sh. DO NOT EDIT.
# Regenerate with: bash tools/gen-dependabot.sh
version: 2
updates:
  - package-ecosystem: gomod
    directories:
EOF
  find . -type f -name go.mod -not -path "./.git/*" -not -path "./.worktrees/*" -not -path "./.claude/*" -exec dirname {} \; \
    | LC_ALL=C sort \
    | while IFS= read -r d; do
      if [ "$d" = "." ]; then
        printf '      - "/"\n'
      else
        printf '      - "%s"\n' "${d#.}"
      fi
    done
  cat <<'EOF'
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    ignore:
      # Temporary: hold grpc until a patched release ships (#309).
      - dependency-name: "google.golang.org/grpc"
    groups:
      go-modules:
        group-by: dependency-name

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
EOF
}

if [ "${1:-}" = "--check" ]; then
  if ! diff -u "$out" <(render); then
    echo "$out is stale: run 'bash tools/gen-dependabot.sh'" >&2
    exit 1
  fi
  echo "$out is up to date"
  exit 0
fi

render > "$out"
echo "wrote $out"
